modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="All Rights Reserved"

[[mods]] #mandatory
modId="mvs" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Moog's Voyager Structures" #mandatory
credits="Special thanks to TelepathicGrunt for helping out!"
authors="finndog" #optional
description='''
A mod that adds over 50 structures into the game, all using vanilla blocks
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.examplemod]]
modId="forge"
mandatory=true
versionRange="[36,]"
ordering="NONE"
side="BOTH"

[[dependencies.examplemod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3, 1.17.0)"
ordering="NONE"
side="BOTH"